version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    command: npm run
    depends_on:
      - db

    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/jobseeker
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    working_dir: /app

  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: jobseeker
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
